### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Eitot** [etresoft/EtreCheck#1]
Do you accept translations?

**Comment by etresoft** [comment]
Hello Eitot,
Sorry I didn't notice your issue. Translations are problem. EtreCheck is very heavily text-based - too much so. Plus, the current usage pattern is to produce a report that other people, such as those on Apple Support Communities, can read and interpret.

I would accept translations, but I think that only the user interface should be translated, not the report itself. That should stay in English. Or perhaps it should have an "export in English" option. 

Anyway, I am planning to re-do the report generation logic. I am going to have the code build an XML document of all the pertinent information and then use XSL to generate the output. So, you wouldn't want to do any translations until after I make this change.

**Comment by Eitot** [comment]
That’s alright. I thought I should suggest it, because I do see the application being used in many places and a translation might help people to understand the reports better.

**Comment by etresoft** [comment]
Cleaning up old issues.
