### ISSUE TITLE
Always says "0" for shutdown code.

### ISSUE THREAD

**Issue by sparky672** [etresoft/EtreCheck#169]
Not sure if this is bug with EtreCheck, or something weird within how logs are written/read.  No matter how I shut down, reboot, etc, or when I run EtreCheck, I **always** get this line at the end:

`Last shutdown cause: 0 - Power loss`

So the first time I noticed it, it was after I clicked the "shut down" button from the dialog box.  Then I decided to reboot by _"Restart..."_ from the Apple menu.  I got the exact same `0 - Power loss` line but with the timestamp of my reboot.

I don't understand how the shutdown code can always be `0` whether I do a full shutdown or a reboot.  Everything else seems normal, nothing is crashing, no kernel panics, no forced shutdowns or reboots.  

Any suggestions appreciated.

**Mid-2012 Mac Pro, Model 5,1** (_not MacBook Pro!_)
6-Core Intel Xeon, 3.33 GHz
Sierra 10.12.6 (16G1114), Kernel Version: Darwin 16.7.0
RAM:  32 GB (_four x 8 GB DDR3 ECC 1333 MHz; all four with same Mfr code `0x80AD` and part number_)
Wireless Card:  BCM94360CD with adapter

_Machine is stock with the exception of the hard drives and wireless card.  Also have a FireWire 400 card in a PCI slot._

**Comment by etresoft** [comment]
Hi sparky672,
The last official documentation of this was around 10.8.5 in [Apple's source code](https://opensource.apple.com/source/PowerManagement/PowerManagement-321.5.3/pmconfigd/PrivateLib.c). Here, 5 was explicitly identified as "Normal Shutdown" and 0 was categorized as "Power loss". There is additional information and good links in [this SO thread](https://apple.stackexchange.com/questions/126588/are-os-x-shutdown-cause-and-sleep-cause-numbers-listed-explained-anywhere/147938). 

Generally, the rationale I use for such things is other EtreCheck reports. If everyone started reporting this shutdown code, then maybe it is normal now. But so far, it looks like 5 is still normal. I shut my machine down the other day and it reported 5. 

If you want more detail, you can use the same procedure that EtreCheck uses and see if you can track down any more information. If you do, please follow up so I can incorporate that in future versions. EtreCheck runs:
system_profiler SPLogsDataType -xml

In the output, it look for section "ioreg_output_description". In that, it looks for the string "ShutdownCause". Here is a small snippet of this section on my machine:

<pre>    | | +-o AppleSMC  &lt;class AppleSMC, id 0x10000039c, registered, matched, active, busy 0 (136 ms), retain 13&gt;
    | |   | {
    | |   |   "IOClass" = "AppleSMC"
    | |   |   "NumIrqMissWithKeyStatOk" = 0x0
    | |   |   "IOPlatformSleepAction" = 0xffffffffffffffff
    | |   |   "ShutdownCause" = "5"
    | |   |   "IOPowerManagement" = {"ChildrenPowerState"=0x1,"CapabilityFlags"=0x8000,"CurrentPowerState"=0x1,"MaxPowerState"=0x1}
    | |   |   "IOProviderClass" = "IOACPIPlatformDevice"
    | |   |   "SleepCause" = "5"
</pre>

For all I know, shutdown cause 0 might be relatively normal on your machine. Another thing you can do is run this [query on Apple Support Communities](https://discussions.apple.com/search.jspa?type=discussion&q=etrecheck+version&sort=updatedDesc&currentPage=1&includeResultCount=true) and look for machines that are similar to yours. You can play around with the search URL if you want, but ASC's search interface is very flaky. You will probably need an ASC account before the search will work reliably for you. You can try a [Google search](https://www.google.com/search?q=%22EtreCheck+version%22+%22MacPro6%2C1%22+site%3Aapple.com&oq=%22EtreCheck+version%22+%22MacPro6%2C1%22+site%3Aapple.com) specifically for your machine too, but Google doesn't seem to have the ability to sort results. You'll get ancient stuff.
