### ISSUE TITLE
User Login Items in Trash

### ISSUE THREAD

**Issue by Eitot** [etresoft/EtreCheck#6]
I noticed that the report lists Login Items of applications that are located in Trash. Perhaps it would be useful to indicate that such programs do not start anymore as long as they are in Trash? In addition, obsolete Login Items could be marked in red, whereas dysfunctional Login Items could be marked in yellow.
```
User Login Items:
<application>    Application  (/Applications/<application>.app)     # Works normally
<application>    UNKNOWN  (missing value)                           # Obsolete
<application>    Application  (~/.Trash/<application>.app)          # Dysfunctional
```

**Comment by etresoft** [comment]
That's a good idea. I have seen reports with items in the trash but I've never looked into it. I should do that. Thanks!

**Comment by etresoft** [comment]
I have just implemented this and it will be in the next release.
