### ISSUE TITLE
Login Items via Service Management framework

### ISSUE THREAD

**Issue by Eitot** [etresoft/EtreCheck#7]
I recently learned (through the application [KnockKnock](https://objective-see.com/products/knockknock.html)) that OS X has another kind of Login Item that is shown neither in System Preferences > Users & Groups > Login Items nor in EtreCheck’s reports. It concerns, for instance, the applications 1Password, Cookie and Dropshelf (all from the App Store). I could not find entries in the LaunchAgents/LaunchDaemons/StartupItems directories either.

According to Apple’s documentation, applications can also be designated as Login Items via the Service Management framework (see [here]( https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLoginItems.html#//apple_ref/doc/uid/10000172i-SW5-BAJJBJEG)) instead of the (in El Capitan deprecated) shared-file list. I am not sure whether this is it though.

Perhaps this is something you may want to add to the reports, as it conceals Login Items that potentially affect the system as well.

The three Login Items in KnockKnock:
![Screenshot of KnockKnock](https://cloud.githubusercontent.com/assets/15073177/12867422/90a2e054-cced-11e5-9f94-21bcf9c56308.png)

Excerpt from the EtreCheck report:
```
Launch Agents: ⓘ
    [running]    at.obdev.LittleSnitchUIAgent.plist [Support]

Launch Daemons: ⓘ
    [running]    at.obdev.littlesnitchd.plist [Support]

User Login Items: ⓘ
    Flux    Application  (/Applications/Caskroom/flux/36-5/Flux.app)
    iTunesHelper    Application  (/Applications/iTunes.app/Contents/MacOS/iTunesHelper.app)
    Amphetamine    Application  (/Applications/Amphetamine.app)
    Dropbox    Application  (/Applications/Caskroom/dropbox/latest/Dropbox.app)
    FunctionFlip    Application  (/Applications/Caskroom/functionflip/2.2.3/FunctionFlip.prefPane/Contents/Resources/FunctionFlip.app)

Other Apps: ⓘ
    [running]    2BUA8C4S2C.com.agilebits.onepassword-osx-helper
    [running]    com.apple.xpc.launchd.oneshot.0x10000006.Cookie
    [running]    com.etresoft.EtreCheck.444512
    [running]    com.getdropbox.dropbox.158432
    [running]    com.if.Amphetamine.157152
    [running]    com.kevingessner.FFHelperApp.164512
    [running]    com.pilotmoon.Dropshelf.48352
    [loaded]    com.pilotmoon.Dropshelf.StartAtLoginHelper
    [loaded]    com.sweetpproductions.Cookie.Helper
    [running]    org.herf.Flux.374752
```

**Comment by etresoft** [comment]
Yes. I added the "Other Apps" section to show these login items and anything else that may have been launched by some of Apple's new Windows-esque methods.
