### ISSUE TITLE
Programm cannot be closed from Dock until started

### ISSUE THREAD

**Issue by Eitot** [etresoft/EtreCheck#8]
Once you open the program, it will present this panel where you have to select a problem and click on ‘Start’. Until you actually did this, you cannot close the window or quit the program from the Dock. Menu bar > Quit seems to work though.

**Comment by etresoft** [comment]
It is a modal dialog so closing the window is probably out of my control. I will have to look into quitting via the dock. That must be some Apple Event.

**Comment by etresoft** [comment]
Found it and fixed it. Will be available in next release.
