### ISSUE TITLE
How to enable Adware check?

### ISSUE THREAD

**Issue by Tekl** [etresoft/EtreCheck#9]
Hi,

I can't see the Adware section in EtreCheck v2.9.12 (265) like in your screenshots. How do I enable it?

I have a copy of Transmission.app in my App folder which is infected by KeRanger. Shouldn't EtreCheck find it? Well, I never launched that App, so the Ransomware is not active. Malwarebytes does find it.

**Comment by etresoft** [comment]
The Adware section will only be displayed if EtreCheck finds adware. EtreCheck is not an anti-malware tool. It only looks for the most common type of adware. It will also identify any unknown launchd scripts. This may catch new adware or potentially some malware. 

But generally, the foundation of Mac security rests on the honesty and/or incompetence of adware/malware authors. If they ever decide to get serious and masquerade as Apple software or popular 3rd party software, there would be no way to detect them. Apple doesn't bother to code-sign its own binaries. There is a new VPN and cloud backup service launched every Tuesday. There is plenty of 3rd party noise to hide in. Most 3rd party Mac anti-malware struggle to keep up with Apple software releases, let alone Mac malware. Malwarebytes does better than most, but has some serious security flaws of its own. Sorry for the bad news...

**Comment by Tekl** [comment]
Thanks for the clarification.

Can you give us more information about the security flaws in Malwarebytes? I've only found a blog entry about the Windows version.

**Comment by etresoft** [comment]
It is not my intention to go around trashing other people's products. Malwarebytes does better than most. But, like EtreCheck, it only detects things when you run it. I frequently see EtreCheck reports with both adware and Malwarebytes installed. Its privileged helper does not have the appropriate password checks either.
